//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lateetud.PrimeritusService.Manager.Primeritus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Primeritus.PrimeritusServiceSoap")]
    public interface PrimeritusServiceSoap {
        
        // CODEGEN: Generating message contract since element name CreatePublisherQueuesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePublisherQueues", ReplyAction="*")]
        Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesResponse CreatePublisherQueues(Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePublisherQueues", ReplyAction="*")]
        System.Threading.Tasks.Task<Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesResponse> CreatePublisherQueuesAsync(Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesRequest request);
        
        // CODEGEN: Generating message contract since element name XmlString from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvokeXmlService", ReplyAction="*")]
        Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceResponse InvokeXmlService(Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvokeXmlService", ReplyAction="*")]
        System.Threading.Tasks.Task<Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceResponse> InvokeXmlServiceAsync(Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePublisherQueuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePublisherQueues", Namespace="http://tempuri.org/", Order=0)]
        public Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesRequestBody Body;
        
        public CreatePublisherQueuesRequest() {
        }
        
        public CreatePublisherQueuesRequest(Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreatePublisherQueuesRequestBody {
        
        public CreatePublisherQueuesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePublisherQueuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePublisherQueuesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesResponseBody Body;
        
        public CreatePublisherQueuesResponse() {
        }
        
        public CreatePublisherQueuesResponse(Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePublisherQueuesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreatePublisherQueuesResult;
        
        public CreatePublisherQueuesResponseBody() {
        }
        
        public CreatePublisherQueuesResponseBody(string CreatePublisherQueuesResult) {
            this.CreatePublisherQueuesResult = CreatePublisherQueuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeXmlServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeXmlService", Namespace="http://tempuri.org/", Order=0)]
        public Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceRequestBody Body;
        
        public InvokeXmlServiceRequest() {
        }
        
        public InvokeXmlServiceRequest(Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvokeXmlServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlString;
        
        public InvokeXmlServiceRequestBody() {
        }
        
        public InvokeXmlServiceRequestBody(string XmlString) {
            this.XmlString = XmlString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeXmlServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeXmlServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceResponseBody Body;
        
        public InvokeXmlServiceResponse() {
        }
        
        public InvokeXmlServiceResponse(Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvokeXmlServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvokeXmlServiceResult;
        
        public InvokeXmlServiceResponseBody() {
        }
        
        public InvokeXmlServiceResponseBody(string InvokeXmlServiceResult) {
            this.InvokeXmlServiceResult = InvokeXmlServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrimeritusServiceSoapChannel : Lateetud.PrimeritusService.Manager.Primeritus.PrimeritusServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrimeritusServiceSoapClient : System.ServiceModel.ClientBase<Lateetud.PrimeritusService.Manager.Primeritus.PrimeritusServiceSoap>, Lateetud.PrimeritusService.Manager.Primeritus.PrimeritusServiceSoap {
        
        public PrimeritusServiceSoapClient() {
        }
        
        public PrimeritusServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrimeritusServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimeritusServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimeritusServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesResponse Lateetud.PrimeritusService.Manager.Primeritus.PrimeritusServiceSoap.CreatePublisherQueues(Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesRequest request) {
            return base.Channel.CreatePublisherQueues(request);
        }
        
        public string CreatePublisherQueues() {
            Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesRequest inValue = new Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesRequest();
            inValue.Body = new Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesRequestBody();
            Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesResponse retVal = ((Lateetud.PrimeritusService.Manager.Primeritus.PrimeritusServiceSoap)(this)).CreatePublisherQueues(inValue);
            return retVal.Body.CreatePublisherQueuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesResponse> Lateetud.PrimeritusService.Manager.Primeritus.PrimeritusServiceSoap.CreatePublisherQueuesAsync(Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesRequest request) {
            return base.Channel.CreatePublisherQueuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesResponse> CreatePublisherQueuesAsync() {
            Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesRequest inValue = new Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesRequest();
            inValue.Body = new Lateetud.PrimeritusService.Manager.Primeritus.CreatePublisherQueuesRequestBody();
            return ((Lateetud.PrimeritusService.Manager.Primeritus.PrimeritusServiceSoap)(this)).CreatePublisherQueuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceResponse Lateetud.PrimeritusService.Manager.Primeritus.PrimeritusServiceSoap.InvokeXmlService(Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceRequest request) {
            return base.Channel.InvokeXmlService(request);
        }
        
        public string InvokeXmlService(string XmlString) {
            Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceRequest inValue = new Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceRequest();
            inValue.Body = new Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceRequestBody();
            inValue.Body.XmlString = XmlString;
            Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceResponse retVal = ((Lateetud.PrimeritusService.Manager.Primeritus.PrimeritusServiceSoap)(this)).InvokeXmlService(inValue);
            return retVal.Body.InvokeXmlServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceResponse> Lateetud.PrimeritusService.Manager.Primeritus.PrimeritusServiceSoap.InvokeXmlServiceAsync(Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceRequest request) {
            return base.Channel.InvokeXmlServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceResponse> InvokeXmlServiceAsync(string XmlString) {
            Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceRequest inValue = new Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceRequest();
            inValue.Body = new Lateetud.PrimeritusService.Manager.Primeritus.InvokeXmlServiceRequestBody();
            inValue.Body.XmlString = XmlString;
            return ((Lateetud.PrimeritusService.Manager.Primeritus.PrimeritusServiceSoap)(this)).InvokeXmlServiceAsync(inValue);
        }
    }
}
